apiVersion: v1
kind: ConfigMap
metadata:
  name: welcome-app-config
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: welcome-app-secret
type: Opaque
data:
  # These are example values encoded in base64
  # In production, use actual secrets management
  API_KEY: YXBpLWtleS1leGFtcGxl
